//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFSpyn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFSpyn.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Sync Pairs.
        /// </summary>
        public static string AllSyncPairsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllSyncPairsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create SyncPair.
        /// </summary>
        public static string MainWindowViewModel_Command_CreateNewSyncPair {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_CreateNewSyncPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View SyncPairs.
        /// </summary>
        public static string MainWindowViewModel_Command_ViewAllSyncPairs {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllSyncPairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spyn.
        /// </summary>
        public static string MainWindowViewModel_DisplayName {
            get {
                return ResourceManager.GetString("MainWindowViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sync Pair.
        /// </summary>
        public static string SyncPairViewModel_DisplayName {
            get {
                return ResourceManager.GetString("SyncPairViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncPair type must be selected.
        /// </summary>
        public static string SyncPairViewModel_Error_MissingSyncPairType {
            get {
                return ResourceManager.GetString("SyncPairViewModel_Error_MissingSyncPairType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save an invalid SyncPair..
        /// </summary>
        public static string SyncPairViewModel_Exception_CannotSave {
            get {
                return ResourceManager.GetString("SyncPairViewModel_Exception_CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Sync.
        /// </summary>
        public static string SyncPairViewModel_SyncPairTypeOption_FullSync {
            get {
                return ResourceManager.GetString("SyncPairViewModel_SyncPairTypeOption_FullSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Not Specified).
        /// </summary>
        public static string SyncPairViewModel_SyncPairTypeOption_NotSpecified {
            get {
                return ResourceManager.GetString("SyncPairViewModel_SyncPairTypeOption_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Sync.
        /// </summary>
        public static string SyncPairViewModel_SyncPairTypeOption_PushSync {
            get {
                return ResourceManager.GetString("SyncPairViewModel_SyncPairTypeOption_PushSync", resourceCulture);
            }
        }
    }
}
