USE [master]
GO

/****** Object:  Database [SPYN]    Script Date: 14/01/2016 4:45:35 PM ******/
CREATE DATABASE [SPYN]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SPYN', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\SPYN.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SPYN_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\SPYN_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SPYN] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SPYN].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SPYN] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SPYN] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SPYN] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SPYN] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SPYN] SET ARITHABORT OFF 
GO

ALTER DATABASE [SPYN] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SPYN] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [SPYN] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SPYN] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SPYN] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SPYN] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SPYN] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SPYN] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SPYN] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SPYN] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SPYN] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SPYN] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SPYN] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SPYN] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SPYN] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SPYN] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SPYN] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SPYN] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SPYN] SET RECOVERY FULL 
GO

ALTER DATABASE [SPYN] SET  MULTI_USER 
GO

ALTER DATABASE [SPYN] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SPYN] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SPYN] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SPYN] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SPYN] SET  READ_WRITE 
GO

